
reset;
model test2.mod;
data test2.dat;

display health_status;


display init_b;
option solver ilogcp;
printf "\n** Before solve **\n\n";
solve;

printf "\n** Results**\n\n";
display satisfaction_children;
display sandwich_in_kitchen;
display sandwich_in_kitchen_non_gluten;
display pos_tray;
display on_tray;
display on_tray_non_gluten;
display tstar;
display bread;
display bread_non_gluten;
display content;
display content_non_gluten;

display make_sandwich;
display make_sandwich_non_gluten;
display put_on_tray;
display put_on_tray_non_gluten;
display move_tray;
display serve;
display serve_non_gluten;
#display tstar;
#display cell;
#display _ampl_elapsed_time;
printf "\n ** For 1D floortile, with %g cells and 1 robot : *"
